In [4]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('Cars_data.csv',encoding='latin1')

In [8]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [10]:
df['Company Names'].value_counts()

Company Names
Nissan               149
Volkswagen           109
Porsche               96
Mazda                 87
Mitsubishi            60
GMC                   59
Chevrolet             58
Ford                  54
Kia                   54
Peugeot               54
TOYOTA                45
BMW                   41
Jaguar Land Rover     40
ROLLS ROYCE           29
Tata Motors           29
Acura                 27
LAMBORGHINI           24
HYUNDAI               23
MERCEDES              21
AUDI                  21
Cadillac              20
Jeep                  19
KIA                   16
ASTON MARTIN          11
NISSAN                10
Tesla                 10
Bugatti               10
FERRARI                9
Volvo                  9
HONDA                  7
Toyota                 5
VOLVO                  3
MAHINDRA               3
MARUTI SUZUKI          3
BENTLEY                1
ROLLS ROYCE            1
KIA                    1
Name: count, dtype: int64

In [11]:
df['Fuel Types'].value_counts()

Fuel Types
Petrol                     871
Diesel                     106
Electric                    97
Hybrid                      79
Petrol/Diesel               16
Petrol/Hybrid               16
Plug-in Hybrid               5
Diesel/Petrol                4
Hybrid (Petrol)              4
Hydrogen                     3
Petrol, Diesel               3
Petrol/AWD                   2
Petrol, Hybrid               2
plug in hyrbrid              1
Petrol/EV                    1
Hybrid/Electric              1
CNG/Petrol                   1
Hybrid/Petrol                1
Diesel Hybrid                1
Petrol (Hybrid)              1
Hybrid (Gas + Electric)      1
Gas / Hybrid                 1
Hybrid / Plug-in             1
Name: count, dtype: int64

In [12]:
pd.get_dummies(df,columns=['Fuel Types'])

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Seats,Torque,...,Fuel Types_Petrol,Fuel Types_Petrol (Hybrid),"Fuel Types_Petrol, Diesel","Fuel Types_Petrol, Hybrid",Fuel Types_Petrol/AWD,Fuel Types_Petrol/Diesel,Fuel Types_Petrol/EV,Fuel Types_Petrol/Hybrid,Fuel Types_Plug-in Hybrid,Fuel Types_plug in hyrbrid
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",2,800 Nm,...,False,False,False,False,False,False,False,False,False,True
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",5,900 Nm,...,True,False,False,False,False,False,False,False,False,False
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",5,100 - 140 Nm,...,True,False,False,False,False,False,False,False,False,False
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",4,900 Nm,...,True,False,False,False,False,False,False,False,False,False
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",2,560 Nm,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"$43,590  $48,000",5,239 Nm,...,False,False,False,False,False,False,False,False,False,False
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",7,630 Nm,...,False,False,False,False,False,False,False,False,False,False
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"$25,210  $29,135",5,190  210 Nm,...,False,False,False,False,False,False,False,False,False,False
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",5,190  205 Nm,...,False,False,False,False,False,False,False,False,False,False
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"$29,000  $43,000",5,221  400 Nm,...,False,False,False,False,False,False,False,False,False,False

<h2>K-1 OneHotEncoding</h2>

In [13]:
pd.get_dummies(df,columns=['Fuel Types'],drop_first=True)

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Seats,Torque,...,Fuel Types_Petrol,Fuel Types_Petrol (Hybrid),"Fuel Types_Petrol, Diesel","Fuel Types_Petrol, Hybrid",Fuel Types_Petrol/AWD,Fuel Types_Petrol/Diesel,Fuel Types_Petrol/EV,Fuel Types_Petrol/Hybrid,Fuel Types_Plug-in Hybrid,Fuel Types_plug in hyrbrid
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",2,800 Nm,...,False,False,False,False,False,False,False,False,False,True
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",5,900 Nm,...,True,False,False,False,False,False,False,False,False,False
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",5,100 - 140 Nm,...,True,False,False,False,False,False,False,False,False,False
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",4,900 Nm,...,True,False,False,False,False,False,False,False,False,False
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",2,560 Nm,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"$43,590  $48,000",5,239 Nm,...,False,False,False,False,False,False,False,False,False,False
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",7,630 Nm,...,False,False,False,False,False,False,False,False,False,False
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"$25,210  $29,135",5,190  210 Nm,...,False,False,False,False,False,False,False,False,False,False
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",5,190  205 Nm,...,False,False,False,False,False,False,False,False,False,False
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"$29,000  $43,000",5,221  400 Nm,...,False,False,False,False,False,False,False,False,False,False

<h2>OneHotEncoding using Sklearn</h2>

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,